version: '3.7'
services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ${REDIS_DB_PATH}:/data
  server:
    image: zyrave/type-graphql-server
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - database
      - redis
    command: ['./wait-for-it.sh', 'database:5432', '--', 'node', 'index.js']
