version: "3.7"
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DOCKER_DATA_PATH}/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${DOCKER_DATA_PATH}/redis:/data
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app/server_dev
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    depends_on:
      - database
      - redis
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "dev"]
